version: "2"
services:
  consul1:
    image: "progrium/consul:latest"
    container_name: "consul1"
    hostname: "consul1"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53"
    command: "-server -bootstrap -ui-dir /ui"
    networks:
      - back
  rabbit_node_1:
    environment:
      - RABBITMQ_ERLANG_COOKIE='secret_cookie'
    networks:
      - back
    depends_on:
      - consul1
    hostname: rabbit_node_1
    image: gsantomaggio/rabbitmq-autocluster
    ports:
      - "15672:15672"
      - "5672:5672"
    tty: true
    volumes:
      - rabbit1:/var/lib/rabbitmq
      - ./conf/:/etc/rabbitmq/
  rabbit_node_2:
    environment:
      - RABBITMQ_ERLANG_COOKIE='secret_cookie'
    networks:
      - back
    hostname: rabbit_node_2
    image: gsantomaggio/rabbitmq-autocluster
    depends_on:
      - rabbit_node_1
      - consul1
    ports:
      - "15673:15672"
      - "5673:5672"
    tty: true
    volumes:
      - rabbit2:/var/lib/rabbitmq
      - ./conf/:/etc/rabbitmq/
 
volumes:
  rabbit1:
    driver: local
  rabbit2:
    driver: local

networks:
  back:
